jwt:
    secret: ${JWT_SECRET}

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.pm.authservice.security: DEBUG
    ROOT: INFO
