spring.application.name=profile-service
server.port=4006
logging.level.root=info

#uncomment to use in memory db outside docker
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#
#spring.datasource.username=admin_viewer
#spring.datasource.password=password
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer

# ---- Kafka basics ----
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.properties.schema.registry.url=http://localhost:8081
spring.kafka.consumer.group-id=profile-service

# optional but handy
spring.kafka.consumer.auto-offset-reset=earliest

# ---------- database connection ----------
spring.datasource.url = jdbc:postgresql://profile-service-db:5002/db
spring.datasource.username = admin_user
spring.datasource.password = password
spring.jpa.database-platform = org.hibernate.dialect.PostgreSQLDialect