### CREATE request to payroll-service
POST http://localhost:4004/api/payroll
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": "11111111-1111-1111-1111-111111111110",
  "dateOfIssue": "2024-07-11"
}

###